### ISSUE TITLE
I'm sorry, I don't know how to use it.

### ISSUE THREAD

**Issue by c02y** [jackkamm/undo-propose-el#10]
So I bind `u` to `undo-propose` in evil-normal-state (I'm using Spacemacs), 

I make some changes in a buffer, and in evil-normal-state, call `u`, and a buffer of `*Undo Propose xxx*` is created, and there is hint in the mode mini buffer

~~~
Undo Propose: C-c C-c to commit buffer....
~~~
But one importance thing, how can I undo the words I insert or undo the deleting I made?

If I call `u` again, it creates another  buffer on top of the undo-propose buffer called `*Undo Propose: *Undo Propose xxx**`, repeatly calling `u` will create undo-propose buffer on the existed buffer repeatly.

If I call `M-x undo`, it says
~~~
Buffer is read-only: xxxx
~~~

I already added `(undo-propose-wrap redo)` into my init.el

How exactly can I undo/redo, and how can I see the undo history?

**Comment by terlar** [comment]
You have to map/call the wrapped `undo` functions. The `undo-propose-wrap` is only remapping bound keys to the given function.

See this for implementation:
https://github.com/jackkamm/undo-propose-el/blob/master/undo-propose.el#L84-L93

If you call `M-x undo` directly you don't call the modified function, by default it remaps whatever you have bound to these two commands, but only the actual bindings. E.g. `C-_` and `C-/`.

**Comment by c02y** [comment]
Could you show me some examples of configuration about how to undo/redo in `*Undo Propose xxx*` buffer?

**Comment by jackkamm** [comment]
Don't bind `undo-propose` to `u`, just leave it bound to `undo`. The idea is to use your regular undo keys in the temp buffer. You can bind `undo-propose` to `SPC o u`, or don't bind it at all and access it through `M-x undo-propose`.

To be extra sure spacemacs/evil isn't doing anything strange to your undo, you can also explicitly disable undo-tree, and explicitly assign `u` to `undo` (though the latter shouldn't be necessary):
```
(global-undo-tree-mode -1)
(evil-global-set-key 'normal (kbd "u") 'undo)
```

**Comment by c02y** [comment]
Yeah, it works now. Thanks.

How about `redo`? It seems currently, `undo` will `undo` all then `redo` all, is there a single `redo` function? I can bind it to `C-r` then.

**Comment by jackkamm** [comment]
Emacs doesn't provide native redo. Instead the emacs way to redo is to break the chain of undo's (e.g. by moving the cursor or pressing `C-g`) and then "undo the undo".

There are various separate packages that provide redo (https://www.emacswiki.org/emacs/RedoMode). Evil's redo is provided by `undo-tree` so if that's disabled then you'll need to install a separate package. You'll also need to wrap the redo command so it works in the undo-propose buffer (see Customization section of the Readme).
