### ISSUE TITLE
Unexpected rendering issue in org mode buffers

### ISSUE THREAD

**Issue by takaxp** [jackkamm/undo-propose-el#19]
Hi.

I input a PR (#18) for suppressing a flicking when activating `undo-propose` in an org buffer. But finally I found out the true reason why the flicking is happened. The reason is the message length in `undo-propose` is over my `frame-width`... :(
It's really unexpected and mystery for me.

Let's look at the demo:
![Untitled](https://user-images.githubusercontent.com/136673/64322954-7d291d00-cffe-11e9-8acc-30a3428f27e6.gif)

The flicking is just stopped when I replaced the original message with `undo-propose: C-c C-c to commit, C-c C-s to squash commit, C-c C-k to cancel` which length is less than 80.

So, do you agree with inclusion of a new user option to control displaying the messages like `undo-propose-verbose`? Of course, the default value is `t`.

If you kindly agree with the addition, I'll create a new PR to provide such capability.

**Comment by jackkamm** [comment]
Here are my thoughts:
1. We should change the message to be less than 80 characters -- it's just good manners. Something like `C-c C-c: commit, C-c C-s: squash commit, C-c C-k: cancel, C-c C-d: diff` (this is 70 characters).
2. If the message above is still too long for you, I am fine with adding an option to suppress the intro message.
3. I think the exit messages on committing/cancelling should not be suppressed. They are short enough anyways that they shouldn't pose a problem.

Feel free to submit a PR for the above if you want to.

**Comment by takaxp** [comment]
Thank you for your kind offer! Actually, I thought I should provide two level verbose options, the fist option will hide all messages and the second option will hide the message in `undo-propose` only. I absolutely welcome your thought 1.

However, adopting your thought 1 may lose consistency because other messages start with "undo-propose:" as prefix. So I think the following code would be better. I already checked the code resolves my issues as well.

```
(message
       (concat (when (> (frame-width) 80) "undo-propose: ")
               "C-c C-c: commit, C-c C-s: squash commit, C-c C-k: cancel, C-c C-d: diff"))
```

or 

```
(let ((prefix "undo-propose: ")
      (content "C-c C-c: commit, C-c C-s: squash commit, C-c C-k: cancel, C-c C-d: diff"))
  (message
   (concat
    (when (> (frame-width)
             (+ (length prefix) (length content)))
      prefix)
    content))
```

The latter is too much?

If you agree with this change, I'm happy to submit a PR regarding this issue.

**Comment by jackkamm** [comment]
The latter is fine by me, it might be even better if it were a function `undo-propose--message` with argument `content`, to replace the other calls to `message`.

**Comment by takaxp** [comment]
Thank you for everything :)
